moyo-core:
- changed-files:
  - any-glob-to-all-files:
    - moyo/**
    - Cargo.toml
    - Cargo.lock

moyopy:
- changed-files:
  - any-glob-to-all-files:
    - moyopy/**

moyoc:
- changed-files:
  - any-glob-to-all-files:
    - moyoc/**

moyo-wasm:
- changed-files:
  - any-glob-to-all-files:
    - moyo-wasm/**

ci:
- changed-files:
  - any-glob-to-all-files:
    - .github/**
