changelog:
  categories:
    - title: 🛠 Breaking Changes
      labels:
        - Semver-Major
        - breaking-changes
    - title: 🎉 New Features
      labels:
        - Semver-Minor
        - enhancement
    - title: ⚙️ moyo-core
      labels:
        - moyo-core
    - title: 🐍 moyopy
      labels:
        - moyopy
    - title: 🧩 moyo-wasm
      labels:
        - moyo-wasm
    - title: 🐞 Bug fixes
      labels:
        - bug
    - title: 📔 Documentation
      labels:
        - documentation
    - title: 🤖 CI
      labels:
        - ci
    - title: 🧹 Other changes
      labels:
        - '*'
