[package]
name = "moyo-wasm"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "WASM bindings for moyo for use in the browser"
repository.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
moyo = { path = "../moyo" }
wasm-bindgen = { version = "0.2", features = ["serde-serialize"] }
serde = { workspace = true }
serde_json = { workspace = true }
nalgebra = { workspace = true }
serde-wasm-bindgen = "0.6"

[features]
default = []
