repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.16.4
    hooks:
      - id: ruff-format
      - id: ruff-check
        args: [ "--fix", "--show-fixes"]
        types_or: [python, pyi]
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.12.5  # uv version.
    hooks:
    - id: uv-lock
