<script lang="ts">
  import HmSymbol from './HmSymbol.svelte'

  // Structural type covering both space- and layer-group Wyckoff DTOs.
  interface WyckoffRow {
    multiplicity: number
    letter: string
    site_symmetry: string
    coordinates: string
  }

  let { positions }: { positions: WyckoffRow[] } = $props()
</script>

<div class="table-shell">
  <table class="min-w-full text-sm font-mono">
    <thead class="table-head">
      <tr>
        <th class="px-2 py-1 text-left">Wyckoff</th>
        <th class="px-2 py-1 text-left">Site symmetry</th>
        <th class="px-2 py-1 text-left">Representative coordinate</th>
      </tr>
    </thead>
    <tbody>
      {#each positions as wp}
        <tr class="border-t border-stone-200 dark:border-stone-800">
          <td class="px-2 py-1 align-top">{wp.multiplicity}{wp.letter}</td>
          <td class="px-2 py-1 align-top"><HmSymbol symbol={wp.site_symmetry} /></td>
          <td class="px-2 py-1 align-top">{wp.coordinates}</td>
        </tr>
      {/each}
    </tbody>
  </table>
</div>
<p class="mt-2 text-xs text-stone-500 dark:text-stone-400">
  {positions.length} Wyckoff position{positions.length === 1 ? '' : 's'}. Only the representative
  coordinate of each position is shown; the remaining equivalent coordinates are generated by the
  symmetry operations above.
</p>
