class PointGroup:
    def __init__(
        self, prim_rotations: list[list[int]], *, basis: list[list[float]] | None = None
    ): ...
    @property
    def arithmetic_number(self) -> int: ...
    @property
    def prim_trans_mat(self) -> list[list[int]]: ...
