use std::collections::HashSet;

use nalgebra::{Dyn, Matrix3, OMatrix, U3, Vector3};
use serde::Serialize;

use super::point_group::{iter_trans_mat_basis, iter_unimodular_trans_mat};
use super::rotation_type::identify_rotation_type;
use super::space_group::match_origin_shift;
use crate::base::{
    Lattice, Operation, Operations, Rotation, Translation, UnimodularLinear,
    UnimodularTransformation, project_rotations,
};
use crate::math::SNF;

///
/// Return integral normalizer of the point group representative up to its centralizer.
///
/// Integral normalizers for all arithmetic point groups up to their centralizers.
/// Generate integral normalizer of the given space group up to its centralizer.
/// Because the factor group of the integral normalizer by the centralizer is isomorphic to a finite permutation group, the output is guaranteed to be finite.
///
/// Be careful that the input primitive operations should be in a reduced basis.
/// This function relies on the bounded search in `iter_unimodular_trans_mat`.
/// For a non-reduced basis, the output is only best effort and may not be exhaustive.
pub fn integral_normalizer(
    prim_operations: &Operations,
    prim_generators: &Operations,
    epsilon: f64,
) -> Vec<UnimodularTransformation> {
    let prim_rotations = project_rotations(prim_operations);
    let prim_rotation_generators = project_rotations(prim_generators);

    let rotation_types = prim_rotations
        .iter()
        .map(identify_rotation_type)
        .collect::<Vec<_>>();

    let mut conjugators = vec![];
    for trans_mat_basis in
        iter_trans_mat_basis(prim_rotations, rotation_types, prim_rotation_generators)
    {
        for prim_trans_mat in iter_unimodular_trans_mat(trans_mat_basis) {
            if let Some(origin_shift) =
                match_origin_shift(prim_operations, &prim_trans_mat, prim_generators, epsilon)
            {
                conjugators.push(UnimodularTransformation::new(prim_trans_mat, origin_shift));
                break;
            }
        }
    }
    conjugators
}

/// Euclidean normalizer of a space group.
///
/// The Euclidean normalizer N_E(G) is the set of affine transformations (P, p)
/// that map G to itself while preserving the metric of the lattice:
///
///   N_E(G) = { (P, p) | (P, p)^{-1} G (P, p) = G,  P^T M P = M }
///
/// Where M is the metric tensor of the primitive lattice. Unlike the affine
/// normalizer, N_E(G) is finite (modulo continuous translations along polar
/// directions) because the metric constraint restricts the linear part to the
/// Bravais group of the lattice.
#[derive(Debug, Clone, Serialize)]
pub struct Normalizer {
    /// Basis vectors for the discrete part of the translation subgroup of the
    /// normalizer modulo Z^3 (in the input primitive basis).
    ///
    /// The full translation subgroup is generated by these vectors together
    /// with the integer lattice Z^3.
    pub translations: Vec<Translation>,
    /// Coset representatives (P, p) of the normalizer modulo its translation
    /// subgroup, in the input primitive basis. The linear part `P` lies in the
    /// Bravais group of the lattice, so `det(P) = +/- 1` (proper when
    /// `det = +1`, improper otherwise).
    pub coset_representatives: Vec<UnimodularTransformation>,
    /// Directions of continuous translations of the normalizer (non-empty for
    /// pyroelectric / polar groups), in the input primitive basis.
    pub continuous_translation_directions: Vec<Vector3<f64>>,
}

impl Normalizer {
    /// Compute the Euclidean normalizer of a space group given in a primitive
    /// basis paired with its primitive lattice.
    ///
    /// `prim_lattice` MUST be the primitive lattice; `prim_operations` and
    /// `prim_generators` MUST be expressed in that primitive basis. Passing a
    /// conventional (non-primitive) lattice is a usage error.
    ///
    /// `epsilon` controls the tolerance for matching metric tensors and origin
    /// shifts. `preserve_chirality = true` restricts the normalizer to the
    /// chirality-preserving subgroup N_E^+(G) (det(P) = +1 only).
    pub fn from_lattice(
        prim_lattice: &Lattice,
        prim_operations: &Operations,
        prim_generators: &Operations,
        epsilon: f64,
        preserve_chirality: bool,
    ) -> Self {
        // Reduce to a Minkowski basis so the Bravais-group enumeration stays
        // bounded for arbitrary input primitive lattices. The reduction matrix
        // may have `det = -1` (orientation flip), which is now handled by
        // `UnimodularTransformation::new` accepting `det = +/- 1`.
        let (reduced_lattice, reduced_trans_mat) = prim_lattice
            .minkowski_reduce()
            .expect("Minkowski reduction failed for the primitive lattice");
        let to_reduced = UnimodularTransformation::from_linear(reduced_trans_mat);
        let reduced_operations = to_reduced.transform_operations(prim_operations);
        let reduced_generators = to_reduced.transform_operations(prim_generators);
        let reduced_rotations = project_rotations(&reduced_operations);
        let reduced_rotation_set: HashSet<Rotation> = reduced_rotations.iter().copied().collect();

        // 1. Bravais group of the reduced primitive lattice.
        let bravais = bravais_group(&reduced_lattice, epsilon);

        // 2. Filter linear parts that conjugate the point group to itself, then
        //    solve for the matching translation via match_origin_shift.
        let mut coset_representatives_reduced = Vec::new();
        for p in &bravais {
            if preserve_chirality {
                let det = p.map(|e| e as f64).determinant().round() as i32;
                if det != 1 {
                    continue;
                }
            }
            let p_inv = p
                .map(|e| e as f64)
                .try_inverse()
                .unwrap()
                .map(|e| e.round() as i32);
            let preserves = reduced_rotations.iter().all(|w| {
                let conjugated = p_inv * w * p;
                reduced_rotation_set.contains(&conjugated)
            });
            if !preserves {
                continue;
            }
            if let Some(origin_shift) =
                match_origin_shift(&reduced_operations, p, &reduced_generators, epsilon)
            {
                coset_representatives_reduced.push(UnimodularTransformation::new(*p, origin_shift));
            }
        }

        // 3. Translation subgroup (discrete part) and continuous directions.
        let translations_reduced = normalizer_translations(&reduced_rotations);
        let continuous_reduced = continuous_translation_directions(&reduced_rotations, epsilon);

        // 4. Map results back to the input primitive basis: under the basis
        //    change matrix T = reduced_trans_mat, a normalizer element
        //    (P_red, p_red) becomes (T P_red T^{-1}, T p_red).
        let to_input = to_reduced.inverse();
        let coset_representatives = coset_representatives_reduced
            .iter()
            .map(|cr| {
                let op = Operation::new(cr.linear, cr.origin_shift);
                let mapped = to_input.transform_operation(&op);
                UnimodularTransformation::new(
                    mapped.rotation,
                    mapped.translation.map(|e| e.rem_euclid(1.0)),
                )
            })
            .collect();

        let trans_mat_f = to_reduced.linear_as_f64();
        let translations = translations_reduced
            .iter()
            .map(|t| (trans_mat_f * t).map(|e| e.rem_euclid(1.0)))
            .collect();
        let continuous_translation_directions =
            continuous_reduced.iter().map(|d| trans_mat_f * d).collect();

        Self {
            translations,
            coset_representatives,
            continuous_translation_directions,
        }
    }
}

/// Enumerate the Bravais group of `lattice`, i.e., the finite group
/// `{ P in GL_3(Z) : P^T M P = M }` where M is the metric tensor.
///
/// Implementation: solve column-by-column. For each i, find integer vectors v
/// with v^T M v == M[i,i]; then for each ordered triple (v0, v1, v2) check the
/// off-diagonal metric entries and |det| = 1.
///
/// The enumeration radius is derived from the metric so it is bounded for any
/// well-conditioned (Minkowski-reduced) basis.
fn bravais_group(lattice: &Lattice, epsilon: f64) -> Vec<UnimodularLinear> {
    let m = lattice.metric_tensor();

    // Column-norm bound: |v_j|^2 <= M_target / lambda_min(M). Use the smallest
    // diagonal entry as a cheap lower bound on the smallest eigenvalue (true
    // for diagonally dominant Minkowski-reduced metrics; if it isn't, we still
    // recover via eigen decomposition below).
    let mut min_eig = m[(0, 0)].min(m[(1, 1)]).min(m[(2, 2)]);
    let eig = m.symmetric_eigenvalues();
    for i in 0..3 {
        if eig[i] > 0.0 && eig[i] < min_eig {
            min_eig = eig[i];
        }
    }
    if min_eig <= 0.0 {
        return Vec::new();
    }
    let max_diag = m[(0, 0)].max(m[(1, 1)]).max(m[(2, 2)]);
    let radius = ((max_diag / min_eig).sqrt().ceil() as i32).max(1);

    // Per-column candidates.
    let candidate_columns: Vec<Vec<Vector3<i32>>> = (0..3)
        .map(|i| {
            let target = m[(i, i)];
            let tol = epsilon * (target.abs() + 1.0);
            let mut cols = Vec::new();
            for vx in -radius..=radius {
                for vy in -radius..=radius {
                    for vz in -radius..=radius {
                        if vx == 0 && vy == 0 && vz == 0 {
                            continue;
                        }
                        let v = Vector3::new(vx, vy, vz);
                        let nrm = quad(&m, &v, &v);
                        if (nrm - target).abs() < tol {
                            cols.push(v);
                        }
                    }
                }
            }
            cols
        })
        .collect();

    let mut result = Vec::new();
    for v0 in &candidate_columns[0] {
        for v1 in &candidate_columns[1] {
            let m01 = quad(&m, v0, v1);
            if (m01 - m[(0, 1)]).abs() > epsilon * (m[(0, 1)].abs() + 1.0) {
                continue;
            }
            for v2 in &candidate_columns[2] {
                let m02 = quad(&m, v0, v2);
                if (m02 - m[(0, 2)]).abs() > epsilon * (m[(0, 2)].abs() + 1.0) {
                    continue;
                }
                let m12 = quad(&m, v1, v2);
                if (m12 - m[(1, 2)]).abs() > epsilon * (m[(1, 2)].abs() + 1.0) {
                    continue;
                }
                let p = Matrix3::from_columns(&[*v0, *v1, *v2]);
                let det = p.map(|e| e as f64).determinant().round() as i32;
                if det.abs() == 1 {
                    result.push(p);
                }
            }
        }
    }
    result
}

/// v^T M w
fn quad(m: &Matrix3<f64>, v: &Vector3<i32>, w: &Vector3<i32>) -> f64 {
    let vf = v.map(|e| e as f64);
    let wf = w.map(|e| e as f64);
    (vf.transpose() * m * wf)[(0, 0)]
}

/// Discrete translation generators of the normalizer's translation subgroup
/// modulo Z^3. Solve `(W - I) p ≡ 0 (mod Z^3)` for all rotations W using SNF.
///
/// Returns a list of fractional translation vectors (in [0, 1)) which together
/// with Z^3 generate the full translation lattice of the normalizer. Excludes
/// the trivial Z^3 generators.
fn normalizer_translations(prim_rotations: &[Rotation]) -> Vec<Translation> {
    if prim_rotations.is_empty() {
        return Vec::new();
    }
    let n = prim_rotations.len();
    let mut a = OMatrix::<i32, Dyn, U3>::zeros(3 * n);
    for (k, w) in prim_rotations.iter().enumerate() {
        let wmi = w - Matrix3::<i32>::identity();
        for i in 0..3 {
            for j in 0..3 {
                a[(3 * k + i, j)] = wmi[(i, j)];
            }
        }
    }
    let snf = SNF::new(&a);
    let mut translations = Vec::new();
    for i in 0..3 {
        let d = snf.d[(i, i)];
        if d > 1 {
            let mut t = Translation::zeros();
            for j in 0..3 {
                t[j] = (snf.r[(j, i)] as f64) / (d as f64);
            }
            translations.push(t.map(|e| e.rem_euclid(1.0)));
        }
    }
    translations
}

/// Real-valued null space of the stacked `(W - I)` matrices: directions p in
/// R^3 such that `(W - I) p = 0` exactly for all rotations W. These are the
/// polar (continuous-translation) directions of the normalizer.
fn continuous_translation_directions(
    prim_rotations: &[Rotation],
    epsilon: f64,
) -> Vec<Vector3<f64>> {
    if prim_rotations.is_empty() {
        return Vec::new();
    }
    let n = prim_rotations.len();
    let mut a = OMatrix::<f64, Dyn, U3>::zeros(3 * n);
    for (k, w) in prim_rotations.iter().enumerate() {
        for i in 0..3 {
            for j in 0..3 {
                let v = w[(i, j)] - if i == j { 1 } else { 0 };
                a[(3 * k + i, j)] = v as f64;
            }
        }
    }
    let svd = a.svd(false, true);
    let s = svd.singular_values;
    let v_t = match svd.v_t {
        Some(v) => v,
        None => return Vec::new(),
    };
    let s_max = s.iter().cloned().fold(0.0_f64, f64::max);
    let tol = epsilon.max(1e-10) * s_max.max(1.0);
    let mut directions = Vec::new();
    for i in 0..s.len().min(3) {
        if s[i].abs() < tol {
            directions.push(Vector3::new(v_t[(i, 0)], v_t[(i, 1)], v_t[(i, 2)]));
        }
    }
    // SVD returns 3 singular values for a 3-column matrix; if the rank is < 3
    // we may have fewer null singular values than directions. Pad from the
    // remaining V^T rows if singular_values has fewer entries than 3.
    if s.len() < 3 {
        for i in s.len()..3 {
            directions.push(Vector3::new(v_t[(i, 0)], v_t[(i, 1)], v_t[(i, 2)]));
        }
    }
    directions
}

#[cfg(test)]
mod tests {
    use std::collections::HashSet;

    use nalgebra::{Vector3, matrix};

    use super::*;
    use crate::base::{EPS, Lattice, Operation};
    use crate::data::HallSymbol;

    fn cubic_lattice(a: f64) -> Lattice {
        Lattice::new(matrix![
            a, 0.0, 0.0;
            0.0, a, 0.0;
            0.0, 0.0, a;
        ])
    }

    fn tetragonal_lattice(a: f64, c: f64) -> Lattice {
        Lattice::new(matrix![
            a, 0.0, 0.0;
            0.0, a, 0.0;
            0.0, 0.0, c;
        ])
    }

    fn hexagonal_lattice(a: f64, c: f64) -> Lattice {
        let s = (3.0_f64).sqrt() / 2.0;
        Lattice::new(matrix![
            a, 0.0, 0.0;
            -0.5 * a, s * a, 0.0;
            0.0, 0.0, c;
        ])
    }

    fn orthorhombic_lattice(a: f64, b: f64, c: f64) -> Lattice {
        Lattice::new(matrix![
            a, 0.0, 0.0;
            0.0, b, 0.0;
            0.0, 0.0, c;
        ])
    }

    /// For Hall symbols whose primitive setting is the standard cubic /
    /// tetragonal / orthorhombic / hexagonal lattice (i.e., centering = P),
    /// pair the primitive operations with a generic lattice respecting the
    /// crystal system and verify each coset rep conjugates G to itself.
    fn assert_normalizer_conjugates_g(
        prim_lattice: &Lattice,
        prim_operations: &Operations,
        prim_generators: &Operations,
        preserve_chirality: bool,
    ) -> Normalizer {
        let normalizer = Normalizer::from_lattice(
            prim_lattice,
            prim_operations,
            prim_generators,
            EPS,
            preserve_chirality,
        );
        let rotations: HashSet<Rotation> = prim_operations.iter().map(|op| op.rotation).collect();
        for cr in &normalizer.coset_representatives {
            let p = cr.linear;
            let p_f = p.map(|e| e as f64);
            let p_inv = p_f.try_inverse().unwrap().map(|e| e.round() as i32);
            let conjugated: HashSet<Rotation> = rotations.iter().map(|w| p_inv * w * p).collect();
            assert_eq!(
                rotations, conjugated,
                "coset rep {:?} did not conjugate G to itself",
                cr
            );
        }
        // Identity is always a coset rep.
        assert!(
            normalizer.coset_representatives.iter().any(|cr| {
                cr.linear == UnimodularLinear::identity()
                    && cr
                        .origin_shift
                        .iter()
                        .all(|&v| (v - v.round()).abs() < 1e-6)
            }),
            "identity not present in coset representatives"
        );
        normalizer
    }

    #[test]
    fn test_bravais_group_cubic() {
        // cP: holohedry m-3m has 48 elements.
        let bravais = bravais_group(&cubic_lattice(1.0), EPS);
        assert_eq!(bravais.len(), 48);
    }

    #[test]
    fn test_bravais_group_tetragonal() {
        // tP: holohedry 4/mmm has 16 elements.
        let bravais = bravais_group(&tetragonal_lattice(1.0, 1.5), EPS);
        assert_eq!(bravais.len(), 16);
    }

    #[test]
    fn test_bravais_group_orthorhombic() {
        // oP: holohedry mmm has 8 elements.
        let bravais = bravais_group(&orthorhombic_lattice(1.0, 1.3, 1.7), EPS);
        assert_eq!(bravais.len(), 8);
    }

    #[test]
    fn test_bravais_group_hexagonal() {
        // hP: holohedry 6/mmm has 24 elements.
        let bravais = bravais_group(&hexagonal_lattice(1.0, 1.5), EPS);
        assert_eq!(bravais.len(), 24);
    }

    #[test]
    fn test_normalizer_p1() {
        // P1 (Hall #1): all of GL_3(Z) up to conjugation, but on a cubic
        // metric the Euclidean normalizer is generated by the cubic Bravais
        // group together with continuous translations along all 3 axes.
        let hall_symbol = HallSymbol::from_hall_number(1).unwrap();
        let prim_operations = hall_symbol.primitive_traverse();
        let prim_generators = hall_symbol.primitive_generators();
        let normalizer = Normalizer::from_lattice(
            &cubic_lattice(1.0),
            &prim_operations,
            &prim_generators,
            EPS,
            false,
        );
        // For a cubic metric, the linear normalizer is the cubic Bravais
        // group (m-3m, 48 elements).
        assert_eq!(normalizer.coset_representatives.len(), 48);
        // P1 is pyroelectric in all 3 directions.
        assert_eq!(normalizer.continuous_translation_directions.len(), 3);
    }

    #[test]
    fn test_normalizer_p_minus_1() {
        // P-1 (Hall #2): point group has {1, -1}. Centrosymmetric, not
        // pyroelectric.
        let hall_symbol = HallSymbol::from_hall_number(2).unwrap();
        let prim_operations = hall_symbol.primitive_traverse();
        let prim_generators = hall_symbol.primitive_generators();
        let normalizer = assert_normalizer_conjugates_g(
            &cubic_lattice(1.0),
            &prim_operations,
            &prim_generators,
            false,
        );
        assert_eq!(normalizer.continuous_translation_directions.len(), 0);
        // On a cubic metric the linear normalizer is the cubic Bravais group.
        assert_eq!(normalizer.coset_representatives.len(), 48);
    }

    #[test]
    fn test_normalizer_pmm2() {
        // Pmm2: polar along z. Build operations directly to avoid relying on
        // a specific Hall-number ordering.
        use nalgebra::matrix;
        let identity = Operation::new(Rotation::identity(), Translation::zeros());
        let two_z = Operation::new(matrix![-1, 0, 0; 0, -1, 0; 0, 0, 1], Translation::zeros());
        let m_x = Operation::new(matrix![-1, 0, 0; 0, 1, 0; 0, 0, 1], Translation::zeros());
        let m_y = Operation::new(matrix![1, 0, 0; 0, -1, 0; 0, 0, 1], Translation::zeros());
        let prim_operations = vec![identity, two_z, m_x.clone(), m_y];
        let prim_generators = vec![m_x];
        let normalizer = assert_normalizer_conjugates_g(
            &orthorhombic_lattice(1.0, 1.3, 1.7),
            &prim_operations,
            &prim_generators,
            false,
        );
        assert_eq!(normalizer.continuous_translation_directions.len(), 1);
    }

    #[test]
    fn test_normalizer_pmmm() {
        // Pmmm: centrosymmetric orthorhombic, built directly.
        use nalgebra::matrix;
        let identity = Rotation::identity();
        let two_z = matrix![-1, 0, 0; 0, -1, 0; 0, 0, 1];
        let two_x = matrix![1, 0, 0; 0, -1, 0; 0, 0, -1];
        let two_y = matrix![-1, 0, 0; 0, 1, 0; 0, 0, -1];
        let inv = -identity;
        let m_x = -two_x;
        let m_y = -two_y;
        let m_z = -two_z;
        let zero = Translation::zeros();
        let prim_operations: Operations = [identity, two_x, two_y, two_z, inv, m_x, m_y, m_z]
            .iter()
            .map(|r| Operation::new(*r, zero))
            .collect();
        let prim_generators = vec![
            Operation::new(two_x, zero),
            Operation::new(two_y, zero),
            Operation::new(inv, zero),
        ];
        let normalizer = assert_normalizer_conjugates_g(
            &orthorhombic_lattice(1.0, 1.3, 1.7),
            &prim_operations,
            &prim_generators,
            false,
        );
        assert_eq!(normalizer.continuous_translation_directions.len(), 0);
    }

    #[test]
    fn test_chirality_preserving_for_sohncke() {
        // P432 (Hall #517 / SG #207): Sohncke (chiral). The full Euclidean
        // normalizer includes improper operations; the chirality-preserving
        // variant should drop them.
        let hall_symbol = HallSymbol::from_hall_number(517).unwrap();
        let prim_operations = hall_symbol.primitive_traverse();
        let prim_generators = hall_symbol.primitive_generators();
        let full = Normalizer::from_lattice(
            &cubic_lattice(1.0),
            &prim_operations,
            &prim_generators,
            EPS,
            false,
        );
        let preserving = Normalizer::from_lattice(
            &cubic_lattice(1.0),
            &prim_operations,
            &prim_generators,
            EPS,
            true,
        );
        assert!(preserving.coset_representatives.len() < full.coset_representatives.len());
        // All preserving reps must have det = +1.
        for cr in &preserving.coset_representatives {
            let det = cr.linear.map(|e| e as f64).determinant().round() as i32;
            assert_eq!(det, 1);
        }
    }

    #[test]
    fn test_normalizer_p43n() {
        // P-43n (Hall #515 / SG #218). Verify the algorithm runs and the
        // identity is included.
        let hall_symbol = HallSymbol::from_hall_number(515).unwrap();
        let prim_operations = hall_symbol.primitive_traverse();
        let prim_generators = hall_symbol.primitive_generators();
        let normalizer = assert_normalizer_conjugates_g(
            &cubic_lattice(1.0),
            &prim_operations,
            &prim_generators,
            false,
        );
        // For P-43n on cubic metric the Euclidean normalizer is Pm-3m with
        // additional half-cell translations; the coset count should divide
        // |B(L)| = 48.
        assert!(48 % normalizer.coset_representatives.len() == 0);
    }

    #[test]
    fn test_normalizer_translation_subgroup_contains_z3() {
        // The translation subgroup always contains Z^3 (trivially), so
        // shifting any operation by an integer vector keeps it in G.
        // The `translations` field returns only the non-trivial cosets.
        // For most space groups it is non-empty (e.g., P-43n has 1/2 1/2 1/2).
        let hall_symbol = HallSymbol::from_hall_number(515).unwrap();
        let prim_operations = hall_symbol.primitive_traverse();
        let prim_generators = hall_symbol.primitive_generators();
        let normalizer = Normalizer::from_lattice(
            &cubic_lattice(1.0),
            &prim_operations,
            &prim_generators,
            EPS,
            false,
        );
        // For each non-trivial translation t, applying (I, t) to G must
        // preserve G modulo Z^3.
        for t in &normalizer.translations {
            let shifted: Operations = prim_operations
                .iter()
                .map(|op| {
                    // (I, t)^{-1} (W, w) (I, t) = (W, w + (W - I) t).
                    let new_t = (op.translation
                        + (op.rotation - Matrix3::<i32>::identity()).map(|e| e as f64) * t)
                        .map(|e| e.rem_euclid(1.0));
                    Operation::new(op.rotation, new_t)
                })
                .collect();
            // The set of (rotation, translation_mod_1) should match.
            let original: HashSet<(Rotation, [i64; 3])> = prim_operations
                .iter()
                .map(|op| (op.rotation, quantize_translation(&op.translation)))
                .collect();
            let new_set: HashSet<(Rotation, [i64; 3])> = shifted
                .iter()
                .map(|op| (op.rotation, quantize_translation(&op.translation)))
                .collect();
            assert_eq!(original, new_set);
        }
    }

    fn quantize_translation(t: &Vector3<f64>) -> [i64; 3] {
        let denom: i64 = 24;
        let denom_f = denom as f64;
        [
            ((t[0] * denom_f).round() as i64).rem_euclid(denom),
            ((t[1] * denom_f).round() as i64).rem_euclid(denom),
            ((t[2] * denom_f).round() as i64).rem_euclid(denom),
        ]
    }
}
