use serde::Serialize;

use super::layer_hall_symbol_database::{LayerHallNumber, LayerNumber};

/// Preference for the Hall setting of a layer group.
///
/// Mirrors [`super::Setting`] for the bulk space-group case: callers either
/// pin a specific [`LayerHallNumber`] or pick a per-LG default (Standard or
/// Spglib). For the v1 layer-group implementation Standard and Spglib agree
/// (paper Fu et al. 2024 Table 5 and `spglib/database/layer_spg.csv` are
/// row-aligned), but the two variants are kept separate so they can diverge
/// without an API break.
#[derive(Debug, Copy, Clone, PartialEq, Serialize)]
pub enum LayerSetting {
    /// A specific Hall number (1 - 116).
    HallNumber(LayerHallNumber),
    /// First Hall row for each LG in spglib's `database/layer_spg.csv`
    /// (ordered by Hall number).
    Spglib,
    /// Paper Fu et al. 2024 Table 5 standard choice (the first row listed
    /// for each LG number).
    Standard,
}

impl Default for LayerSetting {
    fn default() -> Self {
        Self::Standard
    }
}

// Smallest LayerHallNumber per LayerNumber (1..=80). Generated by walking
// `LAYER_HALL_SYMBOL_DATABASE` in hall_number order and recording the first
// occurrence of each LG; the test `test_layer_default_hall_numbers_match_db`
// keeps this in sync.
#[rustfmt::skip]
const LAYER_DEFAULT_HALL_NUMBERS: [LayerHallNumber; 80] = [
    1,   2,   3,   4,   5,   8,   9,   12,  14,  16,
    18,  20,  22,  24,  26,  28,  30,  32,  34,  35,
    37,  38,  39,  40,  42,  43,  44,  46,  48,  50,
    52,  54,  56,  58,  60,  62,  64,  65,  67,  68,
    70,  72,  74,  76,  77,  79,  80,  81,  82,  83,
    84,  85,  87,  88,  89,  90,  91,  92,  93,  94,
    95,  96,  98,  99,  101, 102, 103, 104, 105, 106,
    107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
];

impl LayerSetting {
    /// Hall numbers to try when identifying a layer group from operations.
    /// For per-LG defaults, returns one Hall number per LG (80 entries);
    /// for [`LayerSetting::HallNumber`], returns just that one.
    pub fn hall_numbers(&self) -> Vec<LayerHallNumber> {
        match self {
            LayerSetting::HallNumber(hn) => vec![*hn],
            LayerSetting::Spglib | LayerSetting::Standard => LAYER_DEFAULT_HALL_NUMBERS.to_vec(),
        }
    }

    /// Return the Hall number representing layer group `number` under this
    /// setting. Returns `None` for [`LayerSetting::HallNumber`] (callers
    /// already know the Hall number).
    pub fn hall_number(&self, number: LayerNumber) -> Option<LayerHallNumber> {
        match self {
            LayerSetting::HallNumber(_) => None,
            LayerSetting::Spglib | LayerSetting::Standard => {
                LAYER_DEFAULT_HALL_NUMBERS.get(number as usize - 1).copied()
            }
        }
    }
}

#[cfg(test)]
mod tests {
    use std::collections::HashMap;

    use super::*;
    use crate::data::iter_layer_hall_symbol_entry;

    #[test]
    fn test_layer_default_hall_numbers_match_db() {
        let mut first_seen: HashMap<LayerNumber, LayerHallNumber> = HashMap::new();
        for entry in iter_layer_hall_symbol_entry() {
            first_seen.entry(entry.number).or_insert(entry.hall_number);
        }
        for lg in 1..=80 {
            let expected = *first_seen
                .get(&lg)
                .unwrap_or_else(|| panic!("LG {} missing from database", lg));
            assert_eq!(
                LAYER_DEFAULT_HALL_NUMBERS[(lg - 1) as usize],
                expected,
                "default Hall number for LG {} drifted from database",
                lg
            );
        }
    }

    #[test]
    fn test_hall_numbers_lengths() {
        assert_eq!(LayerSetting::Standard.hall_numbers().len(), 80);
        assert_eq!(LayerSetting::Spglib.hall_numbers().len(), 80);
        assert_eq!(LayerSetting::HallNumber(7).hall_numbers(), vec![7]);
    }

    #[test]
    fn test_hall_number_lookup() {
        assert_eq!(LayerSetting::Standard.hall_number(1), Some(1));
        assert_eq!(LayerSetting::Standard.hall_number(5), Some(5));
        assert_eq!(LayerSetting::Standard.hall_number(80), Some(116));
        assert_eq!(LayerSetting::Standard.hall_number(81), None);
        assert_eq!(LayerSetting::HallNumber(1).hall_number(1), None);
    }

    #[test]
    fn test_default_is_standard() {
        assert_eq!(LayerSetting::default(), LayerSetting::Standard);
    }
}
