#include <assert.h>
#include <math.h>

#include "moyoc.h"

static double determinant(const double a[3][3]) {
    return a[0][0] * (a[1][1] * a[2][2] - a[1][2] * a[2][1])
         - a[0][1] * (a[1][0] * a[2][2] - a[1][2] * a[2][0])
         + a[0][2] * (a[1][0] * a[2][1] - a[1][1] * a[2][0]);
}

static void check_cell(
    const MoyoCell *cell, const double input_basis[3][3],
    const double positions[8][3], const int32_t numbers[8],
    const double linear[3][3], const double shift[3],
    const double rotation[3][3], const int32_t *mapping
) {
    assert(cell->num_atoms == 8);
    assert(determinant(cell->basis) > 0);
    assert(determinant(linear) * determinant(input_basis) > 0);
    // Basis vectors are rows, but linear and rotation are mathematical matrices:
    // A_std = R A_input P with column-wise A.
    for (int i = 0; i < 3; i++) {
        for (int j = 0; j < 3; j++) {
            double expected = 0;
            for (int k = 0; k < 3; k++) {
                for (int l = 0; l < 3; l++) {
                    expected += rotation[j][k] * input_basis[l][k] * linear[l][i];
                }
            }
            assert(fabs(cell->basis[i][j] - expected) < 1e-8);
        }
    }
    for (int i = 0; i < 8; i++) {
        int matches = 0;
        for (int j = 0; j < cell->num_atoms; j++) {
            int match = numbers[i] == cell->numbers[j];
            for (int k = 0; k < 3; k++) {
                double delta = shift[k] - positions[i][k];
                for (int l = 0; l < 3; l++) {
                    delta += linear[k][l] * cell->positions[j][l];
                }
                match &= fabs(delta - round(delta)) < 1e-8;
            }
            if (match) {
                matches++;
                if (mapping != NULL) assert(mapping[i] == j);
            }
        }
        assert(matches == 1);
    }
}

int main(void) {
    // Two generic species orbits generated by the P4_1 screw (-y,x,z+1/4).
    const double seeds[2][3] = {{0.137, 0.271, 0.389}, {0.219, 0.413, 0.157}};
    const double origin[3] = {0.13, 0.27, 0.19};
    for (int handedness = -1; handedness <= 1; handedness += 2) {
        for (int mirrored = 0; mirrored <= 1; mirrored++) {
            // A proper Cartesian rotation followed by the passive shear
            // P = [[1,1,0],[0,1,1],[0,0,handedness]].
            double basis[3][3] = {
                {4, 0, 0}, {4, 2.4, 3.2},
                {0, 2.4 - 4.8 * handedness, 3.2 + 3.6 * handedness},
            };
            // A physical mirror changes only the Cartesian lattice vectors.
            if (mirrored) {
                for (int i = 0; i < 3; i++) basis[i][0] *= -1;
            }
            double positions[8][3];
            int32_t numbers[8];
            for (int species = 0; species < 2; species++) {
                double x = seeds[species][0], y = seeds[species][1];
                for (int n = 0; n < 4; n++) {
                    int i = 4 * species + n;
                    positions[i][2] = (seeds[species][2] + n * 0.25 - origin[2]) / handedness;
                    positions[i][1] = y - origin[1] - positions[i][2];
                    positions[i][0] = x - origin[0] - positions[i][1];
                    numbers[i] = species + 1;
                    double next_x = -y;
                    y = x;
                    x = next_x;
                }
            }
            for (int rotate_basis = 0; rotate_basis <= 1; rotate_basis++) {
                MoyoDataset *dataset = moyo_dataset_new(
                    basis, positions, numbers, 8, 1e-5, -1,
                    MOYO_SETTING_STANDARD, -1, rotate_basis
                );
                assert(dataset != NULL);
                assert(dataset->number == (mirrored ? 78 : 76));
                assert(dataset->hall_number == (mirrored ? 352 : 350));
                assert(dataset->operations.num_operations == 4);
                assert(fabs(determinant(dataset->std_rotation_matrix) - 1) < 1e-8);
                for (int i = 0; i < 3; i++) {
                    for (int j = 0; j < 3; j++) {
                        double dot = 0;
                        for (int k = 0; k < 3; k++) {
                            dot += dataset->std_rotation_matrix[k][i] * dataset->std_rotation_matrix[k][j];
                        }
                        assert(fabs(dot - (i == j)) < 1e-8);
                        if (!rotate_basis) {
                            assert(fabs(dataset->std_rotation_matrix[i][j] - (i == j)) < 1e-8);
                        }
                    }
                }
                check_cell(&dataset->std_cell, basis, positions, numbers,
                    dataset->std_linear, dataset->std_origin_shift,
                    dataset->std_rotation_matrix, NULL);
                check_cell(&dataset->prim_std_cell, basis, positions, numbers,
                    dataset->prim_std_linear, dataset->prim_std_origin_shift,
                    dataset->std_rotation_matrix, dataset->mapping_std_prim);
                moyo_dataset_free(dataset);
            }
        }
    }
    return 0;
}
