name: Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  prek:
    runs-on: ubuntu-latest  # ubuntu-slim lacks cargo
    env:
      SKIP: cbindgen
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
    - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6
      with:
        python-version: '3.13'
    - uses: j178/prek-action@6ad80277337ad479fe43bd70701c3f7f8aa74db3 # v2
      with:
        extra_args: --all-files

  cargo-deny:
    runs-on: ubuntu-latest  # ubuntu-slim lacks docker
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
    - uses: Swatinem/rust-cache@e18b497796c12c097a38f9edb9d0641fb99eee32 # v2
    - uses: EmbarkStudios/cargo-deny-action@6c8f9facfa5047ec02d8485b6bf52b587b7777d1 # v2
      with:
        rust-version: 1.85.0  # edition 2024

  pass:
    name: ✅ Pass checks
    needs: [prek, cargo-deny]
    runs-on: ubuntu-latest # ubuntu-slim lacks python
    steps:
      - name: Check all CI jobs
        uses: re-actors/alls-green@05ac9388f0aebcb5727afa17fcccfecd6f8ec5fe # release/v1
        with:
          jobs: ${{ toJSON(needs) }}
    if: always()
