name: Rust implementation CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    paths:
      - 'moyoc/**'
      - '.github/workflows/ci-rust.yaml'
      - Cargo.toml
      - Cargo.lock
  workflow_dispatch:

env:
  PYTHON_VERSION: "3.11"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: Swatinem/rust-cache@v2
    - name: Install cargo-llvm-cov
      uses: taiki-e/install-action@cargo-llvm-cov
    - name: Test
      run: cargo llvm-cov --release --all-features --workspace --lcov --output-path lcov.info
    - name: Upload coverage to Codecov
      if: github.event.repository.fork == false
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: lcov.info
        fail_ci_if_error: false
  pass:
    name: ✅ Pass ci-rust
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - name: Check all CI jobs
        uses: re-actors/alls-green@release/v1
        with:
          jobs: ${{ toJSON(needs) }}
    if: always()
