name: Publish moyo-wasm to npm

on:
  push:
    tags:
      - v*
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-node@v4
        with:
          node-version: "24"
          registry-url: "https://registry.npmjs.org"

      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown

      - name: Install wasm-pack
        uses: taiki-e/install-action@wasm-pack

      - name: Install test dependencies
        working-directory: moyo-wasm
        run: npm install

      - name: Run tests
        working-directory: moyo-wasm
        run: npm test # this also builds the wasm package to be published in next step

      - name: Publish to npm
        working-directory: moyo-wasm/pkg
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish --access public
