name: Publish moyo-wasm to npm

on:
  push:
    tags:
      - v*
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          registry-url: https://registry.npmjs.org

      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown

      - name: Install wasm-pack
        run: cargo install wasm-pack

      - name: Build wasm package
        run: wasm-pack build moyo-wasm --target web --release

      - name: Install test dependencies
        working-directory: moyo-wasm
        run: npm install

      - name: Run tests
        working-directory: moyo-wasm
        run: npm test

      - name: Publish to npm
        working-directory: moyo-wasm/pkg
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish --access public
