name: C Release CI

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      dry_run:
        description: 'If true, perform a dry run without releasing'
        required: true
        type: boolean

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - os: ubuntu-latest
            target: aarch64-unknown-linux-gnu
          - os: macos-latest
            target: x86_64-apple-darwin
          - os: macos-latest
            target: aarch64-apple-darwin
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}
      - uses: cargo-bins/cargo-binstall@main
      - name: Install cbindgen
        run: cargo binstall cbindgen --locked --no-confirm
      - name: Install cross linker
        if: matrix.target == 'aarch64-unknown-linux-gnu'
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: gcc-aarch64-linux-gnu
          version: 1.0
      - name: Build and package
        shell: bash
        run: |
          if [ "${{ matrix.target }}" = "aarch64-unknown-linux-gnu" ]; then
            export CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER=aarch64-linux-gnu-gcc
          fi
          cd moyoc && make dist TARGET_TRIPLE=${{ matrix.target }}
      - uses: actions/upload-artifact@v4
        with:
          name: moyoc-${{ matrix.target }}
          path: moyoc/dist/moyoc-*-${{ matrix.target }}.*
          if-no-files-found: error

  merge-artifacts:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/upload-artifact/merge@v4
        with:
          name: artifacts
          pattern: moyoc-*

  release:
    if: ${{ ! inputs.dry_run }}
    needs: [merge-artifacts]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: artifacts
          path: artifacts
      - uses: softprops/action-gh-release@v2
        with:
          name: moyoc ${{ github.ref_name }}
          prerelease: ${{ contains(github.ref, 'rc') }}
          files: artifacts/moyoc-*
          fail_on_unmatched_files: true
