name: C binding CI

on:
  workflow_dispatch:
  workflow_call:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
      - uses: Swatinem/rust-cache@e18b497796c12c097a38f9edb9d0641fb99eee32 # v2
      - uses: cargo-bins/cargo-binstall@57726869e28f4038a847ec56e5fdd9142fded110 # main
      - name: Install cbindgen
        run: cargo binstall cbindgen --locked --no-confirm --force
      - name: Configure
        run: cmake -S moyoc -B moyoc/build -DMOYOC_BUILD_FORTRAN=ON
      - name: Build
        run: cmake --build moyoc/build
      - name: Run tests
        run: ctest --test-dir moyoc/build --output-on-failure
