name: C binding CI

on:
  workflow_dispatch:
  workflow_call:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
      - uses: Swatinem/rust-cache@e18b497796c12c097a38f9edb9d0641fb99eee32 # v2
      - uses: cargo-bins/cargo-binstall@802977a265b5f8825ebef2176db5f5f3edc82280 # main
      - name: Install cbindgen
        run: cargo binstall cbindgen --locked --no-confirm --force
      - name: Configure
        run: cmake -S moyoc -B moyoc/build -DMOYOC_BUILD_FORTRAN=ON
      - name: Build
        run: cmake --build moyoc/build
      - name: Run tests
        run: ctest --test-dir moyoc/build --output-on-failure
