name: Python Binding CI

on:
  workflow_dispatch:
  workflow_call:

env:
  PYTHON_VERSION: "3.11"

jobs:
  examples:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Build wheels
        uses: PyO3/maturin-action@v1
        with:
          args: --release --out dist --manifest-path moyopy/Cargo.toml
          sccache: 'true'
          manylinux: auto
      - uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('moyopy/examples/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: examples
        shell: bash
        run: |
          set -e
          uv pip install --system --find-links dist moyopy
          uv pip install --system moyopy[interface]
          find moyopy/examples -name "*.py" | xargs -I {} python {}

  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Build wheels
        uses: PyO3/maturin-action@v1
        with:
          target: x86_64
          args: --release --out dist --manifest-path moyopy/Cargo.toml
          sccache: 'true'
          manylinux: auto
      - name: pytest
        shell: bash
        run: |
          set -e
          uv pip install --system --find-links dist moyopy
          uv pip install --system moyopy[testing,interface]
          pytest -v

  # TODO:
  docs:
    runs-on: ubuntu-latest
    if: "!startsWith(github.ref, 'refs/tags/')"
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: Swatinem/rust-cache@v2
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Build wheels
        uses: PyO3/maturin-action@v1
        with:
          target: x86_64
          args: --release --out dist --manifest-path moyopy/Cargo.toml
          sccache: 'true'
          manylinux: auto
      - name: Install
        run: |
          set -e
          uv pip install --system --find-links dist moyopy
          uv pip install --system moyopy[testing,docs]
      - name: Build
        run: |
          sphinx-build moyopy/docs docs_build
      - name: Deploy
        if: ${{ github.event_name == 'push' }}
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs_build
          destination_dir: python
